name: LFS-warning

on: push

jobs:
  lfs-warning:
    name: LFS Warning
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 

      - name: LFS Warning
        id: lfs_warning
        uses: ActionsDesk/lfs-warning@master
        with:
          filesizelimit: 50mb
  
